spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flight_search?useSSL=false
    username: root
    password:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  #JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
